### ISSUE TITLE
fence_fusion did not work as expected

### ISSUE THREAD

**Issue by hsmanninen** [eedgar/stonith-fences#1]
Tried to get VMware Fusion fencing to work with Fusion 5 from CentOS 6.4 pacemaker node (with Python 2.6.6). The functions for status, on and off were not functioning as expected.

I noticed a problem with the try-expect blocks and made the following change:

try:
        conn.sendline('''IFS=$\'\n\';for x in $(mdfind vmwarevm |grep ".vmwarevm$"); do IFS=$\'\n\';find $x -name *vmx -exec grep -H "Address " {} \; ;done|sort|uniq''')
        conn.log_expect(options, options["-c"], int(options["-g"]))
    except pexpect.EOF:
        fail(EC_CONNECTION_LOST)
    except pexpect.TIMEOUT:
        fail(EC_TIMED_OUT)
    else: # ADDED THIS
        results = conn.before.splitlines()[2:]
        for line in results:
            file, data = line.split(':', 1)
            mac = data.split("= ")[1].strip("\"")
            mac_results.setdefault(file, []).append(mac)

...and added "else:" block to all the other similar places too. Seems to work correctly now as previously it never made it to the result handling.

**Comment by eedgar** [comment]
Can you submit a pull request for this?

**Comment by hsmanninen** [comment]
Yes, did so a while ago.
